spring.application.name=Course-Mgmt-Sys
spring.datasource.url=jdbc:postgresql://localhost:5432/detailsdb
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.security.enabled=false
spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
